### PR TITLE
Fix: #20. Changes to requirements.txt are no longer ignored by GitHub Actions

### LINKED ISSUE #20: requirements.txt is excluded from GitHub Actions
## I expect

- Container to be rebuilt when the requirements.txt changes (which currently will not happen)

See https://github.com/par-tec/super-sast/actions/workflows/publish.yaml

### PR DESCRIPTION
**Pull request by nocturn9x**
Fixes #20

### CODE REVIEW

**Review by ioggstream — CHANGES_REQUESTED** [review]
@nocturn9x why requirements-dev.txt and `pull_requests` are skipped?

**Comment by nocturn9x** [comment]
I wasn't sure whether those had to be included or not. Fixing now

**Comment by nocturn9x** [comment]
Should be fixed now.

**Review by ioggstream — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
